version: '3'

services:
  web:
    image: php:7.4-apache
    container_name: my-php-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      # Set PHP environment variables
      PHP_INI_DISPLAY_ERRORS: On
      PHP_INI_ERROR_REPORTING: E_ALL
      PHP_INI_MEMORY_LIMIT: 512M
      PHP_INI_MAX_EXECUTION_TIME: 300
      PHP_INI_POST_MAX_SIZE: 100M
      PHP_INI_UPLOAD_MAX_FILESIZE: 100M
      APP_WEBHOOKURL: "PLACE DISCORD WEBHOOK URL HERE!"